apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmeter-operator
  namespace: jmeter
spec:
  replicas: 1
  selector:
    matchLabels:
      name: jmeter-operator
  template:
    metadata:
      labels:
        name: jmeter-operator
    spec:
      serviceAccountName: jmeter-operator
      containers:
        - name: jmeter-operator
          # Replace this with the built image name
          image: ironmanrules/jmeter-operator:2.0
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "jmeter-operator"